name: thaibah
description: A new Flutter project.

version: 1.1.4+17

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^6.0.3+2
  connectivity:
  font_awesome_flutter:
  flutter_bloc: ^0.20.0
  flutter_custom_clippers: ^0.1.1
  date_range_picker: ^1.0.5
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  http: ^0.12.0+1
  expandable: ^2.1.1
  provider:
  intl: ^0.15.7
  image_picker:
  image_cropper:
  flutter_image_compress:
  hijri: ^0.2.5
  shared_preferences: ^0.5.6
  url_launcher: ^5.1.2
  flutter_villains: ^1.2.1
  flutter_staggered_grid_view: ^0.3.0
  date_format: ^1.0.6
#  pinput: ^0.1.10
  flutter_svg: ^0.14.2
  flutter_html: ^0.11.0
  flutter_launcher_icons: ^0.7.3
  flutter_screenutil: ^0.4.2
  cached_network_image: any
  flutter_masked_text: ^0.8.0
  flutter_icons: ^0.1.4
  flutter_parallax: "^0.1.2"
  audioplayers: ^0.13.2
  fluttertoast: ^3.1.3
  location: ^2.3.5
#  flutter_lock_screen: ^1.0.5
  rflutter_alert: ^1.0.2
  rich_alert: ^0.1.32
  flutter_swiper: ^1.1.4
  country_code_picker: ^1.1.7
  flutter_country_picker: ^0.1.6
  flutter_webview_plugin: ^0.3.10
  onesignal_flutter: ^2.2.0
  wc_flutter_share: ^0.1.1
  barcode_scan: ^1.0.0
  flutter_youtube: "^2.0.0"
#  loadmore: ^1.0.4
  flutter_local_notifications:
  unicorndial: "^1.1.5"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - assets/
    - assets/images/
    - assets/images/svg/


  fonts:
    - family: Mirza
      fonts:
        - asset: assets/fonts/mirza/Mirza-Medium.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
    - family: ArabicTwo
      fonts:
        - asset: assets/fonts/arabic-two/ArabicTwo.ttf
    - family: NeoSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: NeoSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
