name: thaibah
description: A new Flutter project.

version: 1.1.3+16

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  pin_code_fields: ^2.0.4
#  pin_code_fields: ^2.0.3
#  background_fetch: ^0.3.2
#  google_places_picker: ^2.0.2+2
#  pin_entry_text_field: ^0.1.4
#  need_resume: ^1.0.4
  youtube_player_flutter: ^6.0.3+2
#  flutter_cache_manager: ^1.1.3
#  sticky_headers: "^0.1.8"
#  youtube_player: ^3.5.0
  connectivity:
  font_awesome_flutter:
  flutter_bloc: ^0.20.0
  flutter_custom_clippers: ^0.1.1
  date_range_picker: ^1.0.5
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  http: ^0.12.0+1
  expandable: ^2.1.1
  provider:
  intl: ^0.15.7
  image_picker:
  image_cropper:
  flutter_image_compress:
  hijri: ^0.2.5

#  image_picker:
#  image_picker: "^0.4.5"
#  shared_preferences: ^0.4.2
  shared_preferences: ^0.5.6
#  equatable: ^0.2.0

  url_launcher: ^5.1.2
  flutter_villains: ^1.2.1
  flutter_staggered_grid_view: ^0.3.0
#  numberpicker: ^1.1.0
  date_format: ^1.0.6
  pinput: ^0.1.10
#  pull_to_refresh: ^1.5.7
  flutter_svg: ^0.14.2
#  countdown: ^0.1.0
  flutter_html: ^0.11.0
#  flutube: ^0.8.1

  flutter_launcher_icons: ^0.7.3
  flutter_screenutil: ^0.4.2
  cached_network_image: any
#  extended_image: ^0.6.4
#  flutter_masked_text: ^0.8.0
  flutter_masked_text: ^0.8.0
  flutter_icons: ^0.1.4
  flutter_parallax: "^0.1.2"
  audioplayers: ^0.13.2
  fluttertoast: ^3.1.3
  location: ^2.3.5
#  local_auth: ^0.6.0
  flutter_lock_screen: ^1.0.5
  rflutter_alert: ^1.0.2
  rich_alert: ^0.1.32
#  onesignal: ^1.1.0
  flutter_swiper: ^1.1.4
  country_code_picker: ^1.1.7
  flutter_country_picker: ^0.1.6
  #  dynamic_tabs: ^1.0.2+3
  flutter_webview_plugin: ^0.3.10
  onesignal_flutter: ^2.2.0
#  esys_flutter_share: any
#  web_socket_channel: ^1.0.15
#  flutter_socket_io: ^0.6.0
  wc_flutter_share: ^0.1.1
#  qr_code_scanner: ^0.0.12
  barcode_scan: ^1.0.0
  flutter_youtube: "^2.0.0"
  loadmore: ^1.0.4
  flutter_local_notifications:
#  flutter_compass: ^0.3.4
  unicorndial: "^1.1.5"
#  sqflite: any
#  path_provider: any
#  adhara_socket_io: ^0.4.1
#  firebase_dynamic_links: ^0.5.0+1
#  provider: ^3.0.0
#  location: ^2.3.5
#  geolocator: '^2.0.1'
#  location: ^2.3.5
#  geocoder: ^0.2.1
#  geolocator: ^5.1.5
#  socket_io_client: ^0.9.5
#  image_crop: ^0.3.1
#  image_cropper: ^0.0.4
#  flutter_image_pick_crop: ^0.0.1
#  image_cropper: ^1.1.1
#  flutter_image_compress: ^0.6.0
#  workmanager: ^0.1.5
#  background_fetch: '^0.2.0'
#  adhara_socket_io: ^0.1.0
#  flutter_socket_io: ^0.6.0
#  socket_io_client: ^0.9.7+1
#  hijri: ^0.2.5
#  adhara_socket_io: ^0.4.1
#  socket_io_client: ^0.9.1
#  laravel_echo:

#  socket_io_client: ^0.9.7+1
#  qr_code_scanner:
#    git:
#      url: https://github.com/kiatuki/qr_code_scanner.git
#      ref: 0.0.12-kiatuki.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - assets/
    - assets/images/
    - assets/images/svg/
    - assets/images/ppob/

  fonts:
    - family: Mirza
      fonts:
        - asset: assets/fonts/mirza/Mirza-Medium.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
    - family: ArabicTwo
      fonts:
        - asset: assets/fonts/arabic-two/ArabicTwo.ttf
    - family: NeoSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: NeoSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
