name: thaibah
description: A new Flutter project.

version: 1.2.7+30

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite_at_runtime: ^0.0.1
  infinite_widgets: ^1.0.1
  device_info: ^0.4.1+5
  youtube_player_flutter: ^6.0.3+2
  connectivity:
  font_awesome_flutter:
  flutter_bloc: ^0.20.0
  rxdart: ^0.22.0
  http: ^0.12.0+1
  provider:
  intl: ^0.15.7
  image_picker:
  image_cropper:
  flutter_image_compress:
  shared_preferences: ^0.5.6
  url_launcher: ^5.1.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.14.2
  flutter_html: ^0.11.0
  cached_network_image: any
  audioplayers: ^0.13.2
  location: ^2.3.5
  flutter_swiper: ^1.1.4
  country_code_picker: ^1.1.7
  onesignal_flutter: ^2.2.0
  wc_flutter_share: ^0.1.1
  barcode_scan: ^1.0.0
  unicorndial: "^1.1.5"
  flutter_linkify: ^3.1.0
  app_settings: 3.0.1
  sqflite: any
  path_provider: any
#  google_fonts: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - assets/
    - assets/images/
    - assets/images/svg/


  fonts:

    - family: Rosemary
      fonts:
        - asset: assets/fonts/Rosemary/DroidSans-Bold.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
    - family: ArabicTwo
      fonts:
        - asset: assets/fonts/arabic-two/ArabicTwo.ttf

